networks:
  bridgeautotor:
    name: bridgeautotor
    external: true

services:
  telegram_bot:
    build: .
    container_name: telegram_bot
    env_file:
      - .env
    networks: 
      - bridgeautotor
    volumes:
      - bot_data:/bot
    restart: unless-stopped

volumes:
  bot_data: